// Code generated by acp-go-generator; DO NOT EDIT.

package acp

import (
	"context"
	"encoding/json"
)

func (a *AgentSideConnection) handle(ctx context.Context, method string, params json.RawMessage) (any, *RequestError) {
	switch method {
	case AgentMethodAuthenticate:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p AuthenticateRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		authenticator, ok := a.agent.(AgentAuthenticator)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := authenticator.Authenticate(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodInitialize:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p InitializeRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		resp, err := a.agent.Initialize(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodLogout:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p LogoutRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		logout, ok := a.agent.(AgentLogout)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := logout.Logout(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionCancel:
		if requestErr := requireInboundKind(ctx, InboundNotification, method); requestErr != nil {
			return nil, requestErr
		}
		var p CancelNotification
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		a.mu.Lock()
		if cn, ok := a.sessionCancels[string(p.SessionId)]; ok {
			cn.cancel()
			delete(a.sessionCancels, string(p.SessionId))
		}
		a.mu.Unlock()
		if err := a.agent.Cancel(ctx, p); err != nil {
			return nil, toReqErr(err)
		}
		return nil, nil
	case AgentMethodSessionClose:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p CloseSessionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		closer, ok := a.agent.(AgentSessionCloser)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := closer.CloseSession(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionDelete:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p DeleteSessionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		deleter, ok := a.agent.(AgentSessionDeleter)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := deleter.DeleteSession(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionList:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p ListSessionsRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		lister, ok := a.agent.(AgentSessionLister)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := lister.ListSessions(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionLoad:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p LoadSessionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		loader, ok := a.agent.(AgentLoader)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := loader.LoadSession(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionNew:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p NewSessionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		resp, err := a.agent.NewSession(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionPrompt:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p PromptRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		var reqCtx context.Context
		var cancel context.CancelFunc
		reqCtx, cancel = context.WithCancel(ctx)
		defer cancel()
		entry := &sessionPromptCancel{cancel: cancel}
		a.mu.Lock()
		if prev, ok := a.sessionCancels[string(p.SessionId)]; ok {
			prev.cancel()
		}
		a.sessionCancels[string(p.SessionId)] = entry
		a.mu.Unlock()
		resp, err := a.agent.Prompt(reqCtx, p)
		a.mu.Lock()
		if a.sessionCancels[string(p.SessionId)] == entry {
			delete(a.sessionCancels, string(p.SessionId))
		}
		a.mu.Unlock()
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionResume:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p ResumeSessionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		resumer, ok := a.agent.(AgentSessionResumer)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := resumer.ResumeSession(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionSetConfigOption:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p SetSessionConfigOptionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		configurer, ok := a.agent.(AgentSessionConfig)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := configurer.SetSessionConfigOption(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case AgentMethodSessionSetMode:
		if requestErr := requireInboundKind(ctx, InboundRequest, method); requestErr != nil {
			return nil, requestErr
		}
		var p SetSessionModeRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		modeSetter, ok := a.agent.(AgentSessionMode)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := modeSetter.SetSessionMode(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	default:
		return nil, NewMethodNotFound(method)
	}
}
func (c *AgentSideConnection) CompleteElicitation(ctx context.Context, params CompleteElicitationNotification) error {
	return c.conn.SendNotification(ctx, ClientMethodElicitationComplete, params)
}
func (c *AgentSideConnection) CreateElicitation(ctx context.Context, params CreateElicitationRequest) (CreateElicitationResponse, error) {
	resp, err := SendRequest[CreateElicitationResponse](c.conn, ctx, ClientMethodElicitationCreate, params)
	return resp, err
}
func (c *AgentSideConnection) ReadTextFile(ctx context.Context, params ReadTextFileRequest) (ReadTextFileResponse, error) {
	resp, err := SendRequest[ReadTextFileResponse](c.conn, ctx, ClientMethodFsReadTextFile, params)
	return resp, err
}
func (c *AgentSideConnection) WriteTextFile(ctx context.Context, params WriteTextFileRequest) (WriteTextFileResponse, error) {
	resp, err := SendRequest[WriteTextFileResponse](c.conn, ctx, ClientMethodFsWriteTextFile, params)
	return resp, err
}
func (c *AgentSideConnection) RequestPermission(ctx context.Context, params RequestPermissionRequest) (RequestPermissionResponse, error) {
	resp, err := SendRequest[RequestPermissionResponse](c.conn, ctx, ClientMethodSessionRequestPermission, params)
	return resp, err
}
func (c *AgentSideConnection) SessionUpdate(ctx context.Context, params SessionNotification) error {
	return c.conn.SendNotification(ctx, ClientMethodSessionUpdate, params)
}
func (c *AgentSideConnection) CreateTerminal(ctx context.Context, params CreateTerminalRequest) (CreateTerminalResponse, error) {
	resp, err := SendRequest[CreateTerminalResponse](c.conn, ctx, ClientMethodTerminalCreate, params)
	return resp, err
}
func (c *AgentSideConnection) KillTerminal(ctx context.Context, params KillTerminalRequest) (KillTerminalResponse, error) {
	resp, err := SendRequest[KillTerminalResponse](c.conn, ctx, ClientMethodTerminalKill, params)
	return resp, err
}
func (c *AgentSideConnection) TerminalOutput(ctx context.Context, params TerminalOutputRequest) (TerminalOutputResponse, error) {
	resp, err := SendRequest[TerminalOutputResponse](c.conn, ctx, ClientMethodTerminalOutput, params)
	return resp, err
}
func (c *AgentSideConnection) ReleaseTerminal(ctx context.Context, params ReleaseTerminalRequest) (ReleaseTerminalResponse, error) {
	resp, err := SendRequest[ReleaseTerminalResponse](c.conn, ctx, ClientMethodTerminalRelease, params)
	return resp, err
}
func (c *AgentSideConnection) WaitForTerminalExit(ctx context.Context, params WaitForTerminalExitRequest) (WaitForTerminalExitResponse, error) {
	resp, err := SendRequest[WaitForTerminalExitResponse](c.conn, ctx, ClientMethodTerminalWaitForExit, params)
	return resp, err
}
