// Code generated by acp-go-generator; DO NOT EDIT.

package acp

import (
	"context"
	"encoding/json"
)

func (c *ClientSideConnection) handle(ctx context.Context, method string, params json.RawMessage) (any, *RequestError) {
	switch method {
	case ClientMethodElicitationComplete:
		var p CompleteElicitationNotification
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		completion, ok := c.client.(ClientElicitationCompletion)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		if err := completion.CompleteElicitation(ctx, p); err != nil {
			return nil, toReqErr(err)
		}
		return nil, nil
	case ClientMethodElicitationCreate:
		var p CreateElicitationRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		elicitor, ok := c.client.(ClientElicitation)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := elicitor.CreateElicitation(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodFsReadTextFile:
		var p ReadTextFileRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		reader, ok := c.client.(ClientFileReader)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := reader.ReadTextFile(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodFsWriteTextFile:
		var p WriteTextFileRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		writer, ok := c.client.(ClientFileWriter)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := writer.WriteTextFile(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodSessionRequestPermission:
		var p RequestPermissionRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		resp, err := c.client.RequestPermission(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodSessionUpdate:
		var p SessionNotification
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := c.client.SessionUpdate(ctx, p); err != nil {
			return nil, toReqErr(err)
		}
		return nil, nil
	case ClientMethodTerminalCreate:
		var p CreateTerminalRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		terminal, ok := c.client.(ClientTerminal)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := terminal.CreateTerminal(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodTerminalKill:
		var p KillTerminalRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		terminal, ok := c.client.(ClientTerminal)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := terminal.KillTerminal(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodTerminalOutput:
		var p TerminalOutputRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		terminal, ok := c.client.(ClientTerminal)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := terminal.TerminalOutput(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodTerminalRelease:
		var p ReleaseTerminalRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		terminal, ok := c.client.(ClientTerminal)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := terminal.ReleaseTerminal(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	case ClientMethodTerminalWaitForExit:
		var p WaitForTerminalExitRequest
		if err := json.Unmarshal(params, &p); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		if err := p.Validate(); err != nil {
			return nil, NewInvalidParams(map[string]any{"error": err.Error()})
		}
		terminal, ok := c.client.(ClientTerminal)
		if !ok {
			return nil, NewMethodNotFound(method)
		}
		resp, err := terminal.WaitForTerminalExit(ctx, p)
		if err != nil {
			return nil, toReqErr(err)
		}
		return resp, nil
	default:
		return nil, NewMethodNotFound(method)
	}
}
func (c *ClientSideConnection) Authenticate(ctx context.Context, params AuthenticateRequest) (AuthenticateResponse, error) {
	resp, err := SendRequest[AuthenticateResponse](c.conn, ctx, AgentMethodAuthenticate, params)
	return resp, err
}
func (c *ClientSideConnection) Initialize(ctx context.Context, params InitializeRequest) (InitializeResponse, error) {
	resp, err := SendRequest[InitializeResponse](c.conn, ctx, AgentMethodInitialize, params)
	return resp, err
}
func (c *ClientSideConnection) Logout(ctx context.Context, params LogoutRequest) (LogoutResponse, error) {
	resp, err := SendRequest[LogoutResponse](c.conn, ctx, AgentMethodLogout, params)
	return resp, err
}
func (c *ClientSideConnection) Cancel(ctx context.Context, params CancelNotification) error {
	return c.conn.SendNotification(ctx, AgentMethodSessionCancel, params)
}
func (c *ClientSideConnection) CloseSession(ctx context.Context, params CloseSessionRequest) (CloseSessionResponse, error) {
	resp, err := SendRequest[CloseSessionResponse](c.conn, ctx, AgentMethodSessionClose, params)
	return resp, err
}
func (c *ClientSideConnection) DeleteSession(ctx context.Context, params DeleteSessionRequest) (DeleteSessionResponse, error) {
	resp, err := SendRequest[DeleteSessionResponse](c.conn, ctx, AgentMethodSessionDelete, params)
	return resp, err
}
func (c *ClientSideConnection) ListSessions(ctx context.Context, params ListSessionsRequest) (ListSessionsResponse, error) {
	resp, err := SendRequest[ListSessionsResponse](c.conn, ctx, AgentMethodSessionList, params)
	return resp, err
}
func (c *ClientSideConnection) LoadSession(ctx context.Context, params LoadSessionRequest) (LoadSessionResponse, error) {
	resp, err := SendRequest[LoadSessionResponse](c.conn, ctx, AgentMethodSessionLoad, params)
	return resp, err
}
func (c *ClientSideConnection) NewSession(ctx context.Context, params NewSessionRequest) (NewSessionResponse, error) {
	resp, err := SendRequest[NewSessionResponse](c.conn, ctx, AgentMethodSessionNew, params)
	return resp, err
}
func (c *ClientSideConnection) Prompt(ctx context.Context, params PromptRequest) (PromptResponse, error) {
	resp, err := SendRequest[PromptResponse](c.conn, ctx, AgentMethodSessionPrompt, params)
	return resp, err
}
func (c *ClientSideConnection) ResumeSession(ctx context.Context, params ResumeSessionRequest) (ResumeSessionResponse, error) {
	resp, err := SendRequest[ResumeSessionResponse](c.conn, ctx, AgentMethodSessionResume, params)
	return resp, err
}
func (c *ClientSideConnection) SetSessionConfigOption(ctx context.Context, params SetSessionConfigOptionRequest) (SetSessionConfigOptionResponse, error) {
	resp, err := SendRequest[SetSessionConfigOptionResponse](c.conn, ctx, AgentMethodSessionSetConfigOption, params)
	return resp, err
}
func (c *ClientSideConnection) SetSessionMode(ctx context.Context, params SetSessionModeRequest) (SetSessionModeResponse, error) {
	resp, err := SendRequest[SetSessionModeResponse](c.conn, ctx, AgentMethodSessionSetMode, params)
	return resp, err
}
