package emit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/caelis-labs/acp-go-sdk/cmd/generate/internal/ir"
	"github.com/caelis-labs/acp-go-sdk/cmd/generate/internal/load"
	"github.com/caelis-labs/acp-go-sdk/cmd/generate/internal/util"
)

// splitCamelCase splits a CamelCase string into words.
// Example: "RequestPermissionRequest" -> ["Request", "Permission", "Request"]
func splitCamelCase(s string) []string {
	if s == "" {
		return nil
	}
	var words []string
	var current strings.Builder

	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			// Start new word on uppercase letter
			if current.Len() > 0 {
				words = append(words, current.String())
				current.Reset()
			}
		}
		current.WriteRune(r)
	}
	if current.Len() > 0 {
		words = append(words, current.String())
	}
	return words
}

// generateNestedTypeName applies multiple heuristics to create idiomatic nested type names
// while guaranteeing stability (name depends only on parent, field, and collision check).
//
// If a collision is detected (e.g. the schema already defines a type with the same name we
// would otherwise generate), fall back to a deterministic suffixed name. Panics only if it
// cannot find a unique name (which would indicate a codegen bug).
func generateNestedTypeName(parentName, rawFieldName string, usedNames map[string]bool) string {
	// Heuristic 1: Ensure field name is properly capitalized first
	fieldName := util.ToExportedField(rawFieldName)

	// Heuristic 2: Try RPC suffix stripping for Request/Response/Notification parents
	// This handles cases like RequestPermissionRequest + ToolCall → RequestPermissionToolCall
	for _, suffix := range []string{"Request", "Response", "Notification"} {
		if strings.HasSuffix(parentName, suffix) {
			baseName := strings.TrimSuffix(parentName, suffix)
			if len(baseName) > 0 {
				candidate := baseName + fieldName
				if !usedNames[candidate] {
					return candidate
				}
			}
		}
	}

	// Heuristic 3: Try word-boundary deduplication
	// This handles cases like AgentNotification + ExtNotification → AgentExtNotification
	parentWords := splitCamelCase(parentName)
	fieldWords := splitCamelCase(fieldName)

	// Need at least 2 words in parent to consider deduplication
	if len(parentWords) >= 2 && len(fieldWords) > 0 {
		lastParentWord := parentWords[len(parentWords)-1]
		firstFieldWord := fieldWords[0]
		lastFieldWord := fieldWords[len(fieldWords)-1]

		if strings.EqualFold(lastParentWord, firstFieldWord) || strings.EqualFold(lastParentWord, lastFieldWord) {
			// Remove last word from parent, then concatenate
			parentWithoutLast := strings.Join(parentWords[:len(parentWords)-1], "")
			if len(parentWithoutLast) > 0 {
				candidate := parentWithoutLast + fieldName
				if !usedNames[candidate] {
					return candidate
				}
			}
		}
	}

	// Heuristic 4: Fall back to full concatenation
	fullName := parentName + fieldName
	if !usedNames[fullName] {
		return fullName
	}

	// Collision: this can happen when the schema already defines a top-level type with the
	// same name as an inline property we'd otherwise generate.
	base := fullName + "Inline"
	if !usedNames[base] {
		return base
	}
	for i := 2; i < 1000; i++ {
		candidate := fmt.Sprintf("%s%d", base, i)
		if !usedNames[candidate] {
			return candidate
		}
	}

	// DEFENSIVE PROGRAMMING: If we get here, something is deeply wrong with name tracking.
	panic(fmt.Sprintf("unable to generate unique nested type name (parent: %q, field: %q)", parentName, rawFieldName))
}

// emitDocComment emits a multi-line doc comment for the given description.
// Properly handles newlines and paragraph breaks from JSON schema descriptions.
func emitDocComment(f *File, desc string) {
	lines := util.FormatDocComment(desc)
	for _, line := range lines {
		f.Comment(line)
	}
}

// appendDocComments appends doc comment Code elements to a slice for struct field comments.
// Used when building struct field definitions with proper multi-line comment support.
func appendDocComments(codeSlice []Code, desc string) []Code {
	lines := util.FormatDocComment(desc)
	for _, line := range lines {
		codeSlice = append(codeSlice, Comment(line))
	}
	return codeSlice
}

// WriteTypesJen emits go/types_gen.go with all types and the Agent/Client interfaces.
func WriteTypesJen(outDir string, schema *load.Schema, meta *load.Meta) error {
	f := NewFile("acp")
	f.HeaderComment("Code generated by acp-go-generator; DO NOT EDIT.")

	// Track all type names to avoid collisions when generating nested types
	usedTypeNames := make(map[string]bool)
	for k := range schema.Defs {
		usedTypeNames[k] = true
	}

	// Deterministic order
	keys := make([]string, 0, len(schema.Defs))
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, name := range keys {
		def := schema.Defs[name]
		if def == nil {
			continue
		}

		// DEFENSIVE PROGRAMMING: Ensure we're not about to emit a type that conflicts
		// with a previously generated nested type. This should never happen since we
		// pre-populate usedTypeNames with all schema definitions.
		if usedTypeNames[name] && name != "" {
			// This is expected for schema-defined types, but verify it's in the schema
			if _, inSchema := schema.Defs[name]; !inSchema {
				panic(fmt.Sprintf("BUG: attempting to emit type %q that was already generated as a nested type", name))
			}
		}

		if def.Description != "" {
			emitDocComment(f, def.Description)
		}

		switch {
		case len(def.Enum) > 0:
			f.Type().Id(name).String()
			defs := []Code{}
			for _, v := range def.Enum {
				s := fmt.Sprint(v)
				defs = append(defs, Id(util.ToEnumConst(name, s)).Id(name).Op("=").Lit(s))
			}
			if len(defs) > 0 {
				f.Const().Defs(defs...)
			}
			f.Line()
		case isStringConstUnion(def):
			f.Type().Id(name).String()
			defs := []Code{}
			for _, v := range def.OneOf {
				if v != nil && v.Const != nil {
					s := fmt.Sprint(v.Const)
					defs = append(defs, Id(util.ToEnumConst(name, s)).Id(name).Op("=").Lit(s))
				}
			}
			if len(defs) > 0 {
				f.Const().Defs(defs...)
			}
			f.Line()
		case len(def.AnyOf) > 0 && isOpenStringEnum(def):
			// "Open" string enum: `anyOf` of string consts plus (typically) a
			// free-form string catch-all. Emit as a named string type with
			// constants for the known values. Unknown values are still
			// representable as strings, matching the schema's extensibility.
			f.Type().Id(name).String()
			defs := []Code{}
			for _, v := range def.AnyOf {
				if v == nil || v.Const == nil {
					continue
				}
				s, ok := v.Const.(string)
				if !ok {
					continue
				}
				defs = append(defs, Id(util.ToEnumConst(name, s)).Id(name).Op("=").Lit(s))
			}
			if len(defs) > 0 {
				f.Const().Defs(defs...)
			}
			f.Line()
		case len(def.AnyOf) > 0:
			emitUnion(f, name, schema, def, def.AnyOf, false, usedTypeNames)
		case len(def.OneOf) > 0 && !isStringConstUnion(def):
			// Generic union generation for non-enum oneOf
			// Use the same implementation, but require exactly one variant
			emitUnion(f, name, schema, def, def.OneOf, true, usedTypeNames)
		case ir.PrimaryType(def) == "object" && len(def.Properties) > 0:
			st := []Code{}
			req := map[string]struct{}{}
			for _, r := range def.Required {
				req[r] = struct{}{}
			}
			pkeys := make([]string, 0, len(def.Properties))
			for pk := range def.Properties {
				pkeys = append(pkeys, pk)
			}
			sort.Strings(pkeys)

			// Pre-generate nested struct types for inline object properties
			nestedTypes := map[string]string{} // property name -> generated type name
			for _, pk := range pkeys {
				prop := def.Properties[pk]
				// Detect inline objects: no $ref, type is object, has properties
				if prop.Ref == "" && ir.PrimaryType(prop) == "object" && len(prop.Properties) > 0 {
					nestedTypeName := generateNestedTypeName(name, pk, usedTypeNames)
					nestedTypes[pk] = nestedTypeName

					// DEFENSIVE PROGRAMMING: Assert no collision before registering
					if usedTypeNames[nestedTypeName] {
						panic(fmt.Sprintf("BUG: nested type name collision: %q already registered", nestedTypeName))
					}
					usedTypeNames[nestedTypeName] = true

					// Generate the nested struct type
					if prop.Description != "" {
						emitDocComment(f, prop.Description)
					}
					nestedFields := []Code{}
					nestedReq := map[string]struct{}{}
					for _, r := range prop.Required {
						nestedReq[r] = struct{}{}
					}
					nestedPkeys := make([]string, 0, len(prop.Properties))
					for npk := range prop.Properties {
						nestedPkeys = append(nestedPkeys, npk)
					}
					sort.Strings(nestedPkeys)

					for _, npk := range nestedPkeys {
						nprop := prop.Properties[npk]
						nfield := util.ToExportedField(npk)
						if nprop.Description != "" {
							nestedFields = appendDocComments(nestedFields, nprop.Description)
						}
						ntag := npk
						if _, ok := nestedReq[npk]; !ok {
							ntag = npk + ",omitempty"
						}
						nestedFields = append(nestedFields, Id(nfield).Add(jenTypeForProperty(npk, nprop)).Tag(map[string]string{"json": ntag}))
					}
					f.Type().Id(nestedTypeName).Struct(nestedFields...)
					f.Line()
					if len(prop.Required) > 0 {
						emitRequiredObjectUnmarshal(f, nestedTypeName, schema, prop)
					}
				}
			}

			// Track fields with schema defaults for generic (de)serialization
			type DefaultKind int
			const (
				KindNone DefaultKind = iota
				KindScalar
				KindArray
				KindObject
			)
			type defaultProp struct {
				fieldName   string
				propName    string
				defaultJSON string
				kind        DefaultKind
				allowNull   bool
				nilable     bool // whether zero-value is nil (slice/map)
			}
			defaults := []defaultProp{}

			for _, pk := range pkeys {
				prop := def.Properties[pk]
				field := util.ToExportedField(pk)
				if prop.Description != "" {
					st = appendDocComments(st, prop.Description)
				}
				tag := pk
				// Detect defaults generically
				var dp *defaultProp
				if prop.Default != nil {
					// Compute kind from default value
					k := defaultKindOf(prop.Default)
					// Whether field zero is nil (slice/map) for Marshal fill-in
					nilable := ir.PrimaryType(prop) == "array" || (ir.PrimaryType(prop) == "object" && len(prop.Properties) == 0 && prop.Ref == "")
					// Capture canonical JSON of default
					defJSON := "null"
					if b, err := json.Marshal(prop.Default); err == nil {
						defJSON = string(b)
					}
					dp = &defaultProp{
						fieldName:   field,
						propName:    pk,
						defaultJSON: defJSON,
						kind:        DefaultKind(k),
						allowNull:   includesNull(prop),
						nilable:     nilable,
					}
					defaults = append(defaults, *dp)
				}
				if _, ok := req[pk]; !ok {
					// Default: omit if empty for optional fields.
					// Keep always-present behavior only for defaults where the zero value is nil (slice/map).
					// For typed object defaults (non-nilable), still allow omission on the wire.
					if dp == nil || (dp.kind != KindArray && dp.kind != KindObject) || (dp != nil && !dp.nilable) {
						tag = pk + ",omitempty"
					}
				}
				// Emit an additional comment line indicating the default, if any.
				if dp != nil && dp.defaultJSON != "null" {
					// Insert an empty comment line before default comment (visual separator)
					if prop.Description != "" {
						st = append(st, Comment(""))
					}
					st = append(st, Comment(fmt.Sprintf("Defaults to %s if unset.", dp.defaultJSON)))
				}
				// Use generated nested type if available, otherwise use jenTypeForOptional
				var fieldType Code
				if nestedTypeName, hasNested := nestedTypes[pk]; hasNested {
					fieldType = Id(nestedTypeName)
				} else {
					fieldType = jenTypeForProperty(pk, prop)
				}
				st = append(st, Id(field).Add(fieldType).Tag(map[string]string{"json": tag}))
			}
			f.Type().Id(name).Struct(st...)
			f.Line()

			// If the struct has any fields with schema defaults, synthesize MarshalJSON.
			if len(defaults) > 0 {
				// MarshalJSON: coerce nil slices to empty slices before encoding
				f.Func().Params(Id("v").Id(name)).Id("MarshalJSON").Params().Params(Index().Byte(), Error()).BlockFunc(func(g *Group) {
					g.Type().Id("Alias").Id(name)
					g.Var().Id("a").Id("Alias")
					g.Id("a").Op("=").Id("Alias").Call(Id("v"))
					for _, dp := range defaults {
						// For array/map defaults: if zero is nil, fill with default JSON when nil
						if dp.kind == KindArray || dp.kind == KindObject {
							if dp.nilable {
								g.If(Id("a").Dot(dp.fieldName).Op("==").Nil()).Block(
									Qual("encoding/json", "Unmarshal").Call(Index().Byte().Parens(Lit(dp.defaultJSON)), Op("&").Id("a").Dot(dp.fieldName)),
								)
							}
						}
						// For typed object defaults (non-nilable), we keep Option A: do not inject values on encode.
					}
					g.Return(Qual("encoding/json", "Marshal").Call(Id("a")))
				})
				f.Line()
			}

			// UnmarshalJSON enforces required-property presence and applies defaults
			// when a field is missing or null (and the schema doesn't include null).
			if len(def.Required) > 0 || len(defaults) > 0 {
				f.Func().Params(Id("v").Op("*").Id(name)).Id("UnmarshalJSON").Params(Id("b").Index().Byte()).Error().BlockFunc(func(g *Group) {
					g.Op("*").Id("v").Op("=").Id(name).Values()
					g.Var().Id("m").Map(String()).Qual("encoding/json", "RawMessage")
					g.If(List(Id("err")).Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("m")), Id("err").Op("!=").Nil()).Block(Return(Id("err")))
					emitRequiredPresenceChecks(g, schema, def)
					g.Type().Id("Alias").Id(name)
					g.Var().Id("a").Id("Alias")
					g.If(List(Id("err")).Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("a")), Id("err").Op("!=").Nil()).Block(Return(Id("err")))
					for _, dp := range defaults {
						g.BlockFunc(func(h *Group) {
							h.List(Id("_rm"), Id("_ok")).Op(":=").Id("m").Index(Lit(dp.propName))
							// Apply default when missing, or when null and null is not allowed
							if dp.allowNull {
								h.If(Op("!").Id("_ok")).Block(
									Qual("encoding/json", "Unmarshal").Call(Index().Byte().Parens(Lit(dp.defaultJSON)), Op("&").Id("a").Dot(dp.fieldName)),
								)
							} else {
								h.If(Op("!").Id("_ok").Op("||").Parens(Id("string").Call(Id("_rm")).Op("==").Lit("null"))).Block(
									Qual("encoding/json", "Unmarshal").Call(Index().Byte().Parens(Lit(dp.defaultJSON)), Op("&").Id("a").Dot(dp.fieldName)),
								)
							}
						})
					}
					g.Op("*").Id("v").Op("=").Id(name).Call(Id("a"))
					g.Return(Nil())
				})
				f.Line()
			}
		case ir.PrimaryType(def) == "string" || ir.PrimaryType(def) == "integer" || ir.PrimaryType(def) == "number" || ir.PrimaryType(def) == "boolean":
			f.Type().Id(name).Add(primitiveJenType(def))
			f.Line()
		case ir.PrimaryType(def) == "object" && len(def.Properties) == 0:
			// Empty object shape: emit a concrete empty struct so methods can be defined
			// and the wire encoding is consistently {} rather than null.
			f.Type().Id(name).Struct()
			f.Line()
		default:
			f.Comment(fmt.Sprintf("%s is a union or complex schema; represented generically.", name))
			f.Type().Id(name).Any()
			f.Line()
		}

		// validators for selected types
		// Note: union wrappers get a generic Validate emitted in emitUnion,
		// so skip emitValidateJen for types that already have a union Validate.
		hasUnionValidate := (len(def.OneOf) > 0 || len(def.AnyOf) > 0) && !isStringConstUnion(def) && !isOpenStringEnum(def)
		if !hasUnionValidate && (strings.HasSuffix(name, "Request") || strings.HasSuffix(name, "Response") || strings.HasSuffix(name, "Notification") || name == "ToolCallUpdate") {
			emitValidateJen(f, name, schema, def)
		}
	}

	// Append Agent & Client interfaces from method groups
	groups := ir.BuildMethodGroups(schema, meta)

	// Agent
	agentMethods := []Code{}
	agentAuthenticatorMethods := []Code{}
	agentLogoutMethods := []Code{}
	agentLoaderMethods := []Code{}
	agentSessionCloserMethods := []Code{}
	agentSessionDeleterMethods := []Code{}
	agentSessionListerMethods := []Code{}
	agentSessionResumerMethods := []Code{}
	agentSessionConfigMethods := []Code{}
	agentSessionModeMethods := []Code{}
	agentExperimentalMethods := []Code{}
	for _, k := range ir.SortedKeys(meta.AgentMethods) {
		wire := meta.AgentMethods[k]
		mi := groups["agent|"+wire]
		if mi == nil {
			continue
		}
		target := &agentMethods
		switch mi.Binding {
		case ir.BindAgentAuthenticator:
			target = &agentAuthenticatorMethods
		case ir.BindAgentLogout:
			target = &agentLogoutMethods
		case ir.BindAgentLoader:
			target = &agentLoaderMethods
		case ir.BindAgentSessionCloser:
			target = &agentSessionCloserMethods
		case ir.BindAgentSessionDeleter:
			target = &agentSessionDeleterMethods
		case ir.BindAgentSessionLister:
			target = &agentSessionListerMethods
		case ir.BindAgentSessionResumer:
			target = &agentSessionResumerMethods
		case ir.BindAgentSessionConfig:
			target = &agentSessionConfigMethods
		case ir.BindAgentSessionMode:
			target = &agentSessionModeMethods
		case ir.BindAgentExperimental:
			target = &agentExperimentalMethods
		}
		if desc := methodDescription(schema, mi); desc != "" {
			// Method descriptions can be multi-line, format them properly
			*target = appendDocComments(*target, desc)
		}
		if mi.Notif != "" {
			name := ir.DispatchMethodNameForNotification(k, mi.Notif)
			*target = append(*target, Id(name).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Notif)).Error())
		} else if mi.Req != "" {
			respName := strings.TrimSuffix(mi.Req, "Request") + "Response"
			methodName := strings.TrimSuffix(mi.Req, "Request")
			if ir.IsNullResponse(schema.Defs[respName]) {
				*target = append(*target, Id(methodName).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Req)).Error())
			} else {
				*target = append(*target, Id(methodName).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Req)).Params(Id(respName), Error()))
			}
		}
	}
	f.Type().Id("Agent").Interface(agentMethods...)
	if len(agentAuthenticatorMethods) > 0 {
		f.Comment("AgentAuthenticator defines optional authentication support. Implement it only when Initialize advertises authentication methods.")
		f.Type().Id("AgentAuthenticator").Interface(agentAuthenticatorMethods...)
	}
	if len(agentLogoutMethods) > 0 {
		f.Comment("AgentLogout defines optional logout support. Implement and advertise auth.logout to enable it.")
		f.Type().Id("AgentLogout").Interface(agentLogoutMethods...)
	}
	if len(agentLoaderMethods) > 0 {
		f.Comment("AgentLoader defines optional support for loading sessions. Implement and advertise the capability to enable 'session/load'.")
		f.Type().Id("AgentLoader").Interface(agentLoaderMethods...)
	}
	if len(agentSessionCloserMethods) > 0 {
		f.Comment("AgentSessionCloser defines optional session close support.")
		f.Type().Id("AgentSessionCloser").Interface(agentSessionCloserMethods...)
	}
	if len(agentSessionDeleterMethods) > 0 {
		f.Comment("AgentSessionDeleter defines optional session delete support.")
		f.Type().Id("AgentSessionDeleter").Interface(agentSessionDeleterMethods...)
	}
	if len(agentSessionListerMethods) > 0 {
		f.Comment("AgentSessionLister defines optional session list support.")
		f.Type().Id("AgentSessionLister").Interface(agentSessionListerMethods...)
	}
	if len(agentSessionResumerMethods) > 0 {
		f.Comment("AgentSessionResumer defines optional session resume support.")
		f.Type().Id("AgentSessionResumer").Interface(agentSessionResumerMethods...)
	}
	if len(agentSessionConfigMethods) > 0 {
		f.Comment("AgentSessionConfig defines optional session configuration support.")
		f.Type().Id("AgentSessionConfig").Interface(agentSessionConfigMethods...)
	}
	if len(agentSessionModeMethods) > 0 {
		f.Comment("AgentSessionMode defines optional session mode support.")
		f.Type().Id("AgentSessionMode").Interface(agentSessionModeMethods...)
	}
	if len(agentExperimentalMethods) > 0 {
		f.Comment("AgentExperimental defines unstable methods. Stable generation must not emit this interface.")
		f.Type().Id("AgentExperimental").Interface(agentExperimentalMethods...)
	}

	// Client
	clientStable := []Code{}
	clientFileReader := []Code{}
	clientFileWriter := []Code{}
	clientElicitation := []Code{}
	clientElicitationCompletion := []Code{}
	clientExperimental := []Code{}
	clientTerminal := []Code{}
	for _, k := range ir.SortedKeys(meta.ClientMethods) {
		wire := meta.ClientMethods[k]
		mi := groups["client|"+wire]
		if mi == nil {
			continue
		}
		target := &clientStable
		switch mi.Binding {
		case ir.BindClientFileReader:
			target = &clientFileReader
		case ir.BindClientFileWriter:
			target = &clientFileWriter
		case ir.BindClientElicitation:
			target = &clientElicitation
		case ir.BindClientElicitationCompletion:
			target = &clientElicitationCompletion
		case ir.BindClientExperimental:
			target = &clientExperimental
		case ir.BindClientTerminal:
			target = &clientTerminal
		}
		if desc := methodDescription(schema, mi); desc != "" {
			// Method descriptions can be multi-line, format them properly
			*target = appendDocComments(*target, desc)
		}
		if mi.Notif != "" {
			name := ir.DispatchMethodNameForNotification(k, mi.Notif)
			*target = append(*target, Id(name).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Notif)).Error())
		} else if mi.Req != "" {
			respName := strings.TrimSuffix(mi.Req, "Request") + "Response"
			methodName := strings.TrimSuffix(mi.Req, "Request")
			if ir.IsNullResponse(schema.Defs[respName]) {
				*target = append(*target, Id(methodName).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Req)).Error())
			} else {
				*target = append(*target, Id(methodName).Params(Id("ctx").Qual("context", "Context"), Id("params").Id(mi.Req)).Params(Id(respName), Error()))
			}
		}
	}
	f.Type().Id("Client").Interface(clientStable...)
	if len(clientFileReader) > 0 {
		f.Comment("ClientFileReader defines optional text-file read support.")
		f.Type().Id("ClientFileReader").Interface(clientFileReader...)
	}
	if len(clientFileWriter) > 0 {
		f.Comment("ClientFileWriter defines optional text-file write support.")
		f.Type().Id("ClientFileWriter").Interface(clientFileWriter...)
	}
	if len(clientElicitation) > 0 {
		f.Comment("ClientElicitation defines optional structured elicitation support.")
		f.Type().Id("ClientElicitation").Interface(clientElicitation...)
	}
	if len(clientElicitationCompletion) > 0 {
		f.Comment("ClientElicitationCompletion defines optional URL elicitation completion notifications.")
		f.Type().Id("ClientElicitationCompletion").Interface(clientElicitationCompletion...)
	}
	if len(clientTerminal) > 0 {
		f.Comment("ClientTerminal defines optional terminal support. Implement and advertise terminal to enable terminal methods.")
		f.Type().Id("ClientTerminal").Interface(clientTerminal...)
	}
	if len(clientExperimental) > 0 {
		f.Comment("ClientExperimental defines unstable methods. Stable generation must not emit this interface.")
		f.Type().Id("ClientExperimental").Interface(clientExperimental...)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "types_gen.go"), buf.Bytes(), 0o644)
}

func isStringConstUnion(def *load.Definition) bool {
	if def == nil || len(def.OneOf) == 0 {
		return false
	}
	for _, v := range def.OneOf {
		if v == nil || v.Const == nil {
			return false
		}
		if _, ok := v.Const.(string); !ok {
			return false
		}
	}
	return true
}

// isOpenStringEnum reports whether def is an "open" string enum: an `anyOf`
// where every variant is a plain string schema (type: "string") and at least
// one variant has a string `const`. Such schemas describe a string value with
// a recommended set of known values while still permitting arbitrary strings
// for extensibility (see e.g. SessionConfigOptionCategory).
//
// These are emitted as a Go string-derived type with named constants for each
// known value, rather than as a discriminated union wrapper.
func isOpenStringEnum(def *load.Definition) bool {
	if def == nil || len(def.AnyOf) == 0 {
		return false
	}
	sawConst := false
	for _, v := range def.AnyOf {
		if v == nil {
			return false
		}
		// Each variant must be a plain string schema: type "string", no nested
		// structure (properties, items, refs, nested unions, allOf, etc.).
		if ir.PrimaryType(v) != "string" {
			return false
		}
		if v.Ref != "" || len(v.Properties) > 0 || v.Items != nil ||
			len(v.AnyOf) > 0 || len(v.OneOf) > 0 || len(v.AllOf) > 0 ||
			len(v.Enum) > 0 {
			return false
		}
		if v.Const != nil {
			if _, ok := v.Const.(string); !ok {
				return false
			}
			sawConst = true
		}
	}
	return sawConst
}

func emitRequiredPresenceChecks(g *Group, schema *load.Schema, def *load.Definition) {
	required := append([]string(nil), def.Required...)
	sort.Strings(required)
	for _, propName := range required {
		prop := def.Properties[propName]
		allowsNull := definitionAllowsNull(schema, prop, make(map[*load.Definition]bool))
		g.BlockFunc(func(h *Group) {
			if allowsNull {
				h.List(Id("_"), Id("ok")).Op(":=").Id("m").Index(Lit(propName))
			} else {
				h.List(Id("raw"), Id("ok")).Op(":=").Id("m").Index(Lit(propName))
			}
			h.If(Op("!").Id("ok")).Block(
				Return(Qual("fmt", "Errorf").Call(Lit(propName + " is required"))),
			)
			if !allowsNull {
				h.If(Qual("bytes", "Equal").Call(Qual("bytes", "TrimSpace").Call(Id("raw")), Index().Byte().Parens(Lit("null")))).Block(
					Return(Qual("fmt", "Errorf").Call(Lit(propName + " must not be null"))),
				)
			}
		})
	}
}

func emitRequiredObjectUnmarshal(f *File, name string, schema *load.Schema, def *load.Definition) {
	f.Func().Params(Id("v").Op("*").Id(name)).Id("UnmarshalJSON").Params(Id("b").Index().Byte()).Error().BlockFunc(func(g *Group) {
		g.Op("*").Id("v").Op("=").Id(name).Values()
		g.Var().Id("m").Map(String()).Qual("encoding/json", "RawMessage")
		g.If(List(Id("err")).Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("m")), Id("err").Op("!=").Nil()).Block(Return(Id("err")))
		emitRequiredPresenceChecks(g, schema, def)
		g.Type().Id("Alias").Id(name)
		g.Var().Id("a").Id("Alias")
		g.If(List(Id("err")).Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("a")), Id("err").Op("!=").Nil()).Block(Return(Id("err")))
		g.Op("*").Id("v").Op("=").Id(name).Call(Id("a"))
		g.Return(Nil())
	})
	f.Line()
}

// emitValidateJen generates semantic validators that can be evaluated from a
// Go value alone. Wire-level required-property presence is enforced by the
// generated UnmarshalJSON methods.

func emitValidateJen(f *File, name string, schema *load.Schema, def *load.Definition) {
	if def != nil && ir.PrimaryType(def) == "object" {
		if name != "ToolCallUpdate" && !strings.HasSuffix(name, "Request") && !strings.HasSuffix(name, "Response") && !strings.HasSuffix(name, "Notification") {
			return
		}
		f.Func().Params(Id("v").Op("*").Id(name)).Id("Validate").Params().Params(Error()).BlockFunc(func(g *Group) {
			required := append([]string(nil), def.Required...)
			sort.Strings(required)
			for _, propName := range required {
				property := def.Properties[propName]
				field := util.ToExportedField(propName)
				allowsNull := definitionAllowsNull(schema, property, make(map[*load.Definition]bool))
				switch ir.PrimaryType(property) {
				case "array":
					if !allowsNull {
						g.If(Id("v").Dot(field).Op("==").Nil()).Block(
							Return(Qual("fmt", "Errorf").Call(Lit(propName + " is required"))),
						)
					}
					if validator := generatedValidatorName(schema, property.Items); validator != "" {
						g.For(List(Id("i")).Op(":=").Range().Id("v").Dot(field)).BlockFunc(func(loop *Group) {
							loop.If(List(Id("err")).Op(":=").Id("v").Dot(field).Index(Id("i")).Dot("Validate").Call(), Id("err").Op("!=").Nil()).Block(
								Return(Qual("fmt", "Errorf").Call(Lit(propName+"[%d]: %w"), Id("i"), Id("err"))),
							)
						})
					}
				case "object":
					if property.Ref == "" && len(property.Properties) == 0 && !allowsNull {
						g.If(Id("v").Dot(field).Op("==").Nil()).Block(
							Return(Qual("fmt", "Errorf").Call(Lit(propName + " is required"))),
						)
					}
				}
				if validator := generatedValidatorName(schema, property); validator != "" {
					validate := func(group *Group) {
						group.If(List(Id("err")).Op(":=").Id("v").Dot(field).Dot("Validate").Call(), Id("err").Op("!=").Nil()).Block(
							Return(Qual("fmt", "Errorf").Call(Lit(propName+": %w"), Id("err"))),
						)
					}
					if includesNull(property) {
						g.If(Id("v").Dot(field).Op("!=").Nil()).BlockFunc(validate)
					} else {
						validate(g)
					}
				}
			}
			g.Return(Nil())
		})
	}
}

func generatedValidatorName(schema *load.Schema, definition *load.Definition) string {
	if schema == nil || definition == nil {
		return ""
	}
	ref := definition.Ref
	if ref == "" {
		for _, part := range definition.AllOf {
			if part != nil && part.Ref != "" {
				ref = part.Ref
				break
			}
		}
	}
	if !strings.HasPrefix(ref, "#/$defs/") {
		return ""
	}
	name := ref[len("#/$defs/"):]
	target := schema.Defs[name]
	if target == nil {
		return ""
	}
	hasUnionValidate := (len(target.OneOf) > 0 || len(target.AnyOf) > 0) && !isStringConstUnion(target) && !isOpenStringEnum(target)
	if hasUnionValidate || name == "ToolCallUpdate" ||
		(ir.PrimaryType(target) == "object" && (strings.HasSuffix(name, "Request") || strings.HasSuffix(name, "Response") || strings.HasSuffix(name, "Notification"))) {
		return name
	}
	return ""
}

func methodDescription(schema *load.Schema, mi *ir.MethodInfo) string {
	if mi == nil || mi.DocsIgnored {
		return ""
	}
	// Prefer notification descriptions when present, otherwise fall back to request/response types.
	ordered := []string{mi.Notif, mi.Req, mi.Resp}
	for _, name := range ordered {
		if name == "" {
			continue
		}
		if def := schema.Defs[name]; def != nil && def.Description != "" {
			return def.Description
		}
	}
	return ""
}

// Type mapping helpers (unchanged behavior vs original)
func primitiveJenType(def *load.Definition) Code {
	if def == nil {
		return Any()
	}
	switch ir.PrimaryType(def) {
	case "string":
		return String()
	case "integer":
		switch def.Format {
		case "int8":
			return Id("int8")
		case "int16":
			return Id("int16")
		case "int32":
			return Id("int32")
		case "int64":
			return Id("int64")
		case "uint8":
			return Id("uint8")
		case "uint16":
			return Id("uint16")
		case "uint32":
			return Id("uint32")
		case "uint64":
			return Id("uint64")
		default:
			// JSON Schema integer is platform-independent. Use int64 rather than
			// Go's architecture-sized int when no narrower format is declared.
			return Id("int64")
		}
	case "number":
		return Float64()
	case "boolean":
		return Bool()
	default:
		return Any()
	}
}

// defaultKindOf classifies the JSON Schema default value into a coarse kind.
func defaultKindOf(val any) int {
	switch val.(type) {
	case nil:
		return 0 // KindNone
	case []any:
		return 2 // KindArray
	case map[string]any:
		return 3 // KindObject
	case string, float64, bool:
		return 1 // KindScalar
	default:
		// Fallback: classify by fmt string
		s := fmt.Sprint(val)
		if strings.HasPrefix(s, "[") {
			return 2
		}
		if strings.HasPrefix(s, "map[") || strings.HasPrefix(s, "{") {
			return 3
		}
		return 1
	}
}

// includesNull reports whether the property's type union contains null.
func includesNull(d *load.Definition) bool {
	if d == nil {
		return false
	}
	if arr, ok := d.Type.([]any); ok {
		for _, v := range arr {
			if s, ok2 := v.(string); ok2 && s == "null" {
				return true
			}
		}
	}
	for _, candidate := range append(append([]*load.Definition(nil), d.AnyOf...), d.OneOf...) {
		if candidate != nil && ir.PrimaryType(candidate) == "null" {
			return true
		}
	}
	return false
}

func definitionAllowsNull(schema *load.Schema, d *load.Definition, seen map[*load.Definition]bool) bool {
	if d == nil || seen[d] {
		return false
	}
	seen[d] = true
	defer delete(seen, d)
	if includesNull(d) || ir.PrimaryType(d) == "null" {
		return true
	}
	if d.Ref != "" && schema != nil && strings.HasPrefix(d.Ref, "#/$defs/") {
		return definitionAllowsNull(schema, schema.Defs[d.Ref[len("#/$defs/"):]], seen)
	}
	for _, candidate := range d.AllOf {
		if definitionAllowsNull(schema, candidate, seen) {
			return true
		}
	}
	return false
}

// expandAllOf merges JSON Schema allOf nodes into a shallow composite definition.
//
// ACP's schema frequently uses `allOf: [{"$ref": "#/$defs/Type"}]` so a property or union
// variant can attach local metadata (description/default/const constraints) while reusing
// a referenced shape.
//
// For codegen purposes we approximate allOf by merging object properties + required lists.
// We intentionally do not attempt to resolve semantic constraints beyond that.
func expandAllOf(schema *load.Schema, d *load.Definition) *load.Definition {
	if d == nil || len(d.AllOf) == 0 {
		return d
	}

	merged := *d
	// Avoid re-processing in recursive calls.
	merged.AllOf = nil

	if d.Properties != nil {
		merged.Properties = make(map[string]*load.Definition, len(d.Properties))
		for k, v := range d.Properties {
			merged.Properties[k] = v
		}
	}
	if d.Required != nil {
		merged.Required = append([]string(nil), d.Required...)
	}

	reqSet := map[string]struct{}{}
	for _, r := range merged.Required {
		reqSet[r] = struct{}{}
	}

	for _, part := range d.AllOf {
		if part == nil {
			continue
		}
		resolved := part
		if part.Ref != "" && schema != nil && strings.HasPrefix(part.Ref, "#/$defs/") {
			if def := schema.Defs[part.Ref[len("#/$defs/"):]]; def != nil {
				resolved = def
			}
		}
		resolved = expandAllOf(schema, resolved)

		if merged.Type == nil && resolved.Type != nil {
			merged.Type = resolved.Type
		}
		if merged.Format == "" && resolved.Format != "" {
			merged.Format = resolved.Format
		}
		if merged.Items == nil && resolved.Items != nil {
			merged.Items = resolved.Items
		}
		if merged.Ref == "" && resolved.Ref != "" {
			merged.Ref = resolved.Ref
		}
		if len(merged.Enum) == 0 && len(resolved.Enum) > 0 {
			merged.Enum = resolved.Enum
		}
		if len(merged.AnyOf) == 0 && len(resolved.AnyOf) > 0 {
			merged.AnyOf = resolved.AnyOf
		}
		if len(merged.OneOf) == 0 && len(resolved.OneOf) > 0 {
			merged.OneOf = resolved.OneOf
		}
		if merged.AdditionalProperties == nil && resolved.AdditionalProperties != nil {
			merged.AdditionalProperties = resolved.AdditionalProperties
		}
		if merged.UnevaluatedProperties == nil && resolved.UnevaluatedProperties != nil {
			merged.UnevaluatedProperties = resolved.UnevaluatedProperties
		}

		if len(resolved.Properties) > 0 {
			if merged.Properties == nil {
				merged.Properties = make(map[string]*load.Definition)
			}
			for k, v := range resolved.Properties {
				if _, ok := merged.Properties[k]; ok {
					continue
				}
				merged.Properties[k] = v
			}
		}
		for _, r := range resolved.Required {
			if _, ok := reqSet[r]; ok {
				continue
			}
			merged.Required = append(merged.Required, r)
			reqSet[r] = struct{}{}
		}
	}

	return &merged
}

func jenTypeFor(d *load.Definition) Code {
	if d == nil {
		return Any()
	}

	// JSON Schema 2020-12 commonly uses allOf wrappers around a single $ref so a property can
	// attach local metadata like descriptions and defaults.
	if len(d.AllOf) > 0 && d.Ref == "" {
		// Prefer a $ref element when present.
		for _, e := range d.AllOf {
			if e != nil && e.Ref != "" {
				return jenTypeFor(e)
			}
		}
		// Otherwise fall back to the first non-nil schema.
		for _, e := range d.AllOf {
			if e != nil {
				return jenTypeFor(e)
			}
		}
	}

	if d.Ref != "" {
		if strings.HasPrefix(d.Ref, "#/$defs/") {
			return Id(d.Ref[len("#/$defs/"):])
		}
		return Any()
	}
	if len(d.Enum) > 0 {
		return String()
	}
	switch ir.PrimaryType(d) {
	case "string":
		return String()
	case "integer":
		return primitiveJenType(d)
	case "number":
		return Float64()
	case "boolean":
		return Bool()
	case "array":
		return Index().Add(jenTypeFor(d.Items))
	case "object":
		if len(d.Properties) == 0 {
			return Map(String()).Any()
		}
		return Map(String()).Any()
	default:
		if len(d.AnyOf) > 0 || len(d.OneOf) > 0 {
			return Any()
		}
		return Any()
	}
}

// jenTypeForOptional maps unions that include null to pointer types where applicable.
func jenTypeForOptional(d *load.Definition) Code {
	if d == nil {
		return Any()
	}
	list := d.AnyOf
	if len(list) == 0 {
		list = d.OneOf
	}
	// Case: property type is a union like ["string","null"]
	if arr, ok := d.Type.([]any); ok && len(arr) == 2 {
		var other string
		for _, v := range arr {
			if s, ok2 := v.(string); ok2 {
				if s == "null" {
					continue
				}
				other = s
			}
		}
		switch other {
		case "string":
			return Op("*").String()
		case "integer":
			return Op("*").Add(primitiveJenType(d))
		case "number":
			return Op("*").Float64()
		case "boolean":
			return Op("*").Bool()
		}
	}
	if len(list) == 2 {
		var nonNull *load.Definition
		for _, e := range list {
			if e == nil {
				continue
			}
			if s, ok := e.Type.(string); ok && s == "null" {
				continue
			}
			if e.Const != nil {
				nn := *e
				nn.Type = "string"
				nonNull = &nn
			} else {
				nonNull = e
			}
		}
		if nonNull != nil {
			if nonNull.Ref != "" && strings.HasPrefix(nonNull.Ref, "#/$defs/") {
				return Op("*").Id(nonNull.Ref[len("#/$defs/"):])
			}
			switch ir.PrimaryType(nonNull) {
			case "string":
				return Op("*").String()
			case "integer":
				return Op("*").Add(primitiveJenType(nonNull))
			case "number":
				return Op("*").Float64()
			case "boolean":
				return Op("*").Bool()
			}
		}
	}
	return jenTypeFor(d)
}

// jenTypeForProperty preserves extension metadata as raw JSON values. Decoding
// _meta into map[string]any would coerce JSON numbers to float64 and corrupt
// valid values that cannot be represented exactly by IEEE-754 doubles.
func jenTypeForProperty(name string, d *load.Definition) Code {
	if name == "_meta" {
		return Map(String()).Qual("encoding/json", "RawMessage")
	}
	return jenTypeForOptional(d)
}

func isTrueSchema(value any) bool {
	enabled, ok := value.(bool)
	return ok && enabled
}

func preservesRawPayload(def *load.Definition) bool {
	return def != nil && (isTrueSchema(def.AdditionalProperties) || isTrueSchema(def.UnevaluatedProperties))
}

func unionRequiredAlternatives(schema *load.Schema, def *load.Definition) [][]string {
	if def == nil {
		return nil
	}
	alternatives := make([][]string, 0, len(def.AnyOf))
	for _, candidate := range def.AnyOf {
		candidate = expandAllOf(schema, candidate)
		if candidate == nil || len(candidate.Required) == 0 {
			continue
		}
		required := append([]string(nil), candidate.Required...)
		sort.Strings(required)
		alternatives = append(alternatives, required)
	}
	return alternatives
}

func unionAlternativeProperties(schema *load.Schema, def *load.Definition) map[string]*load.Definition {
	properties := make(map[string]*load.Definition)
	if def == nil {
		return properties
	}
	for _, candidate := range def.AnyOf {
		candidate = expandAllOf(schema, candidate)
		if candidate == nil {
			continue
		}
		for name, property := range candidate.Properties {
			properties[name] = property
		}
	}
	return properties
}

// emitAvailableCommandInputJen generates a concrete variant type for anyOf and a thin union wrapper
// that supports JSON unmarshal by probing object shape. Currently the schema defines one variant
// (title: UnstructuredCommandInput) with a required 'hint' field.
func emitUnion(f *File, name string, schema *load.Schema, parentDef *load.Definition, defs []*load.Definition, exactlyOne bool, usedTypeNames map[string]bool) {
	type variantInfo struct {
		fieldName         string
		typeName          string
		required          []string
		isObject          bool
		isArray           bool
		arrayItemRequired []string
		discValue         string
		constPairs        [][2]string
		literalConst      any
		isNull            bool
		preserveRaw       bool
		requiredAnyOf     [][]string
		alternativeProps  map[string]*load.Definition
		properties        map[string]*load.Definition
		description       string
	}
	variants := []variantInfo{}
	discKey := ""
	// Use schema's explicit discriminator if available
	if parentDef != nil && parentDef.Discriminator != nil {
		discKey = parentDef.Discriminator.PropertyName
	}
	// Fallback: discover discriminator key by scanning for const properties
	// (for backward compatibility with older schemas without discriminator metadata)
	if discKey == "" {
		for _, v := range defs {
			if v == nil {
				continue
			}
			v = expandAllOf(schema, v)
			for k, pd := range v.Properties {
				if pd != nil && pd.Const != nil {
					discKey = k
					break
				}
			}
			if discKey != "" {
				break
			}
		}
	}
	sharedProps := map[string]*load.Definition{}
	sharedRequired := map[string]struct{}{}
	if parentDef != nil {
		for k, p := range parentDef.Properties {
			sharedProps[k] = p
		}
		for _, r := range parentDef.Required {
			sharedRequired[r] = struct{}{}
		}
	}

	for idx, v := range defs {
		if v == nil {
			continue
		}
		ref := v.Ref
		// If this is an allOf wrapper around a single $ref with no additional structure, treat it
		// as a $ref variant (keeps types stable and avoids duplicate structs).
		if ref == "" &&
			v.Type == nil &&
			len(v.Properties) == 0 &&
			len(v.Required) == 0 &&
			len(v.Enum) == 0 &&
			v.Items == nil &&
			len(v.AnyOf) == 0 &&
			len(v.OneOf) == 0 &&
			len(v.AllOf) == 1 &&
			v.AllOf[0] != nil &&
			v.AllOf[0].Ref != "" {
			ref = v.AllOf[0].Ref
		}
		v = expandAllOf(schema, v)
		// A union with sibling object properties means every variant contains
		// those shared properties. A referenced variant therefore cannot reuse
		// the referenced Go type directly: doing so would silently drop the
		// sibling fields. Emit a parent-scoped wrapper containing both shapes.
		if ref != "" && len(sharedProps) > 0 && strings.HasPrefix(ref, "#/$defs/") {
			if len(v.Properties) == 0 {
				if referenced := schema.Defs[ref[len("#/$defs/"):]]; referenced != nil {
					resolved := expandAllOf(schema, referenced)
					copyDef := *v
					copyDef.Properties = make(map[string]*load.Definition, len(resolved.Properties))
					for key, property := range resolved.Properties {
						copyDef.Properties[key] = property
					}
					copyDef.Required = append(append([]string(nil), v.Required...), resolved.Required...)
					v = &copyDef
				}
			}
			ref = ""
		}
		// Detect null-only variant
		isNull := false
		if s, ok := v.Type.(string); ok && s == "null" {
			isNull = true
		}
		// Determine type name: prefer $ref target name when present; do not treat Title as a rename for $ref.
		tname := ""
		if ref != "" && strings.HasPrefix(ref, "#/$defs/") {
			tname = ref[len("#/$defs/"):]
		} else if v.Title != "" {
			// Scope inline variant titles to parent union name with smart naming
			tname = generateNestedTypeName(name, v.Title, usedTypeNames)
			// DEFENSIVE PROGRAMMING: Assert no collision before registering
			if usedTypeNames[tname] {
				panic(fmt.Sprintf("BUG: variant type name collision: %q already registered (parent: %q, title: %q)",
					tname, name, v.Title))
			}
			usedTypeNames[tname] = true
		} else {
			if discKey != "" {
				if pd := v.Properties[discKey]; pd != nil && pd.Const != nil {
					s := fmt.Sprint(pd.Const)
					tname = generateNestedTypeName(name, s, usedTypeNames)
					// DEFENSIVE PROGRAMMING: Assert no collision before registering
					if usedTypeNames[tname] {
						panic(fmt.Sprintf("BUG: variant type name collision: %q already registered (parent: %q, discriminator: %q)",
							tname, name, s))
					}
					usedTypeNames[tname] = true
				}
			}
			if tname == "" {
				tname = name + fmt.Sprintf("Variant%d", idx+1)
				// DEFENSIVE PROGRAMMING: Assert no collision before registering
				if usedTypeNames[tname] {
					panic(fmt.Sprintf("BUG: variant type name collision: %q already registered (parent: %q)",
						tname, name))
				}
				usedTypeNames[tname] = true
			}
		}
		// Ensure Title-derived names are exported (e.g., "stdio" -> "Stdio").
		tname = util.ToExportedField(tname)

		// Derive field name with priority: discriminator value > title > type name
		fieldName := ""
		dv := ""

		// Priority 1: Use discriminator const value (most ergonomic)
		if discKey != "" {
			if pd := v.Properties[discKey]; pd != nil && pd.Const != nil {
				s := fmt.Sprint(pd.Const)
				fieldName = util.ToExportedField(s)
				dv = s
			}
		}

		// Priority 2: Use original title if no discriminator (e.g., "stdio")
		if fieldName == "" && v.Title != "" {
			fieldName = util.ToExportedField(v.Title)
		}

		// Priority 3: Fall back to type name
		if fieldName == "" {
			fieldName = util.ToExportedField(tname)
		}
		isObj := len(v.Properties) > 0
		preserveRaw := preservesRawPayload(v)
		isArray := ir.PrimaryType(v) == "array"
		requiredAnyOf := unionRequiredAlternatives(schema, v)
		alternativeProps := unionAlternativeProperties(schema, v)
		variantProperties := make(map[string]*load.Definition, len(sharedProps)+len(v.Properties)+len(alternativeProps))
		for propertyName, property := range alternativeProps {
			variantProperties[propertyName] = property
		}
		for propertyName, property := range sharedProps {
			variantProperties[propertyName] = property
		}
		for propertyName, property := range v.Properties {
			variantProperties[propertyName] = property
		}
		arrayItemRequired := []string{}
		if isArray && v.Items != nil {
			item := v.Items
			if item.Ref != "" && strings.HasPrefix(item.Ref, "#/$defs/") {
				if d := schema.Defs[item.Ref[len("#/$defs/"):]]; d != nil {
					item = d
				}
			}
			item = expandAllOf(schema, item)
			if ir.PrimaryType(item) == "object" && len(item.Required) > 0 {
				arrayItemRequired = append(arrayItemRequired, item.Required...)
				sort.Strings(arrayItemRequired)
			}
		}
		// Skip phantom variants that have neither $ref nor object shape nor null nor title
		// (but allow title-only variants like ExtMethodRequest to generate as empty structs)
		if !isObj && ref == "" && !isNull && v.Title == "" {
			continue
		}
		// collect const properties (e.g., type, outcome)
		consts := [][2]string{}
		for pk, pd := range v.Properties {
			if pd != nil && pd.Const != nil {
				if s, ok := pd.Const.(string); ok {
					consts = append(consts, [2]string{pk, s})
				}
			}
		}
		// Emit struct for inline variants (non-$ref)
		if (isObj || isNull || v.Title != "") && ref == "" {
			// DEFENSIVE PROGRAMMING: Verify tname is registered before emitting
			if !usedTypeNames[tname] {
				panic(fmt.Sprintf("BUG: attempting to emit unregistered type: %q (parent union: %q)", tname, name))
			}

			st := []Code{}
			if preserveRaw {
				if v.Description != "" {
					emitDocComment(f, v.Description)
				}
				f.Type().Id(tname).Op("=").Qual("encoding/json", "RawMessage")
				f.Line()
				goto skipStructEmit
			} else if !isNull && isObj {
				req := map[string]struct{}{}
				for _, r := range v.Required {
					req[r] = struct{}{}
				}
				for r := range sharedRequired {
					req[r] = struct{}{}
				}
				mergedProps := variantProperties
				pkeys := make([]string, 0, len(mergedProps))
				for pk := range mergedProps {
					pkeys = append(pkeys, pk)
				}
				sort.Strings(pkeys)
				if v.Description != "" {
					emitDocComment(f, v.Description)
				}
				for _, pk := range pkeys {
					pDef := mergedProps[pk]
					field := util.ToExportedField(pk)
					if pDef.Description != "" {
						st = appendDocComments(st, pDef.Description)
					}
					tag := pk
					if _, ok := req[pk]; !ok {
						tag = pk + ",omitempty"
					}
					fieldType := jenTypeForProperty(pk, pDef)
					if _, fromAlternative := alternativeProps[pk]; fromAlternative && !includesNull(pDef) {
						fieldType = Op("*").Add(jenTypeFor(pDef))
					}
					st = append(st, Id(field).Add(fieldType).Tag(map[string]string{"json": tag}))
				}
			} else if !isNull && !isObj && v.Title != "" {
				// Title-only variants: check if they're extension types
				// Extension types should preserve the raw payload, not drop it
				isExtension := strings.Contains(strings.ToLower(v.Description), "extension") ||
					strings.Contains(v.Title, "Ext")

				if v.Description != "" {
					emitDocComment(f, v.Description)
				}

				if isExtension {
					// Emit as type alias (=) to json.RawMessage to preserve marshal/unmarshal methods.
					// Using type alias ensures the RawMessage methods are inherited, unlike a defined type.
					f.Type().Id(tname).Op("=").Qual("encoding/json", "RawMessage")
				} else if ir.PrimaryType(v) != "" {
					// Non-object title-only variants can still carry payloads (e.g. arrays).
					// Emit a concrete type so sequential decode can succeed for valid payloads.
					f.Type().Id(tname).Add(jenTypeFor(v))
				} else {
					// Emit as empty struct only for truly empty variants.
					f.Type().Id(tname).Struct(st...)
				}
				f.Line()
				// Skip the struct emission below for title-only variants
				goto skipStructEmit
			}
			f.Type().Id(tname).Struct(st...)
			f.Line()
		skipStructEmit:
		}
		variantRequired := append([]string(nil), v.Required...)
		for required := range sharedRequired {
			if !slices.Contains(variantRequired, required) {
				variantRequired = append(variantRequired, required)
			}
		}
		sort.Strings(variantRequired)
		variants = append(variants, variantInfo{
			fieldName:         fieldName,
			typeName:          tname,
			required:          variantRequired,
			isObject:          isObj,
			isArray:           isArray,
			arrayItemRequired: arrayItemRequired,
			discValue:         dv,
			constPairs:        consts,
			literalConst:      v.Const,
			isNull:            isNull,
			preserveRaw:       preserveRaw,
			requiredAnyOf:     requiredAnyOf,
			alternativeProps:  alternativeProps,
			properties:        variantProperties,
			description:       v.Description,
		})
	}
	// wrapper
	st := []Code{}
	for _, vi := range variants {
		if vi.description != "" {
			st = appendDocComments(st, vi.description)
		}
		st = append(st, Id(vi.fieldName).Op("*").Id(vi.typeName).Tag(map[string]string{"json": "-"}))
	}
	f.Type().Id(name).Struct(st...)
	f.Line()
	emitAlternativeValueMatch := func(group *Group, matchVar, propertyName string, property *load.Definition) {
		group.BlockFunc(func(check *Group) {
			check.List(Id("raw"), Id("ok")).Op(":=").Id("m").Index(Lit(propertyName))
			check.If(Op("!").Id("ok")).Block(Id(matchVar).Op("=").Lit(false))
			check.If(Id("ok")).BlockFunc(func(present *Group) {
				if !definitionAllowsNull(schema, property, make(map[*load.Definition]bool)) {
					present.If(Id("string").Call(Id("raw")).Op("==").Lit("null")).Block(Id(matchVar).Op("=").Lit(false))
				}
				present.Var().Id("value").Add(jenTypeFor(property))
				present.If(Qual("encoding/json", "Unmarshal").Call(Id("raw"), Op("&").Id("value")).Op("!=").Nil()).Block(Id(matchVar).Op("=").Lit(false))
			})
		})
	}
	// Unmarshal
	f.Func().Params(Id("u").Op("*").Id(name)).Id("UnmarshalJSON").Params(Id("b").Index().Byte()).Error().BlockFunc(func(g *Group) {
		// A receiver may be reused by callers or decoder pools. Clear every
		// previously selected variant before attempting the next decode.
		g.Op("*").Id("u").Op("=").Id(name).Values()
		// Handle literal null if a null-only variant exists
		{
			varNullHandled := false
			for _, vi := range variants {
				if vi.isNull {
					// emit once for the first null variant
					if !varNullHandled {
						g.If(Id("string").Call(Id("b")).Op("==").Lit("null")).Block(
							Var().Id("v").Id(vi.typeName),
							Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v"),
							Return(Nil()),
						)
						varNullHandled = true
					}
				}
			}
		}
		g.Var().Id("m").Map(String()).Qual("encoding/json", "RawMessage")
		g.If(List(Id("err")).Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("m")), Id("err").Op("==").Nil()).BlockFunc(func(obj *Group) {
			// Prefer discriminator-based dispatch when available (e.g. "type", "outcome")
			if discKey != "" {
				obj.BlockFunc(func(h *Group) {
					h.Var().Id("disc").String()
					h.If(List(Id("v"), Id("ok")).Op(":=").Id("m").Index(Lit(discKey)), Id("ok")).Block(
						Qual("encoding/json", "Unmarshal").Call(Id("v"), Op("&").Id("disc")),
					)
					h.Switch(Id("disc")).BlockFunc(func(sw *Group) {
						for _, vi := range variants {
							if vi.discValue != "" {
								sw.Case(Lit(vi.discValue)).BlockFunc(func(variant *Group) {
									for _, rk := range vi.required {
										property := vi.properties[rk]
										allowsNull := definitionAllowsNull(schema, property, make(map[*load.Definition]bool))
										variant.BlockFunc(func(required *Group) {
											required.List(Id("raw"), Id("ok")).Op(":=").Id("m").Index(Lit(rk))
											required.If(Op("!").Id("ok")).Block(Return(Qual("errors", "New").Call(Lit("invalid variant payload"))))
											if !allowsNull {
												required.If(Qual("bytes", "Equal").Call(Qual("bytes", "TrimSpace").Call(Id("raw")), Index().Byte().Parens(Lit("null")))).Block(
													Return(Qual("errors", "New").Call(Lit("invalid variant payload"))),
												)
											}
											required.Var().Id("value").Add(jenTypeFor(property))
											required.If(Qual("encoding/json", "Unmarshal").Call(Id("raw"), Op("&").Id("value")).Op("!=").Nil()).Block(
												Return(Qual("errors", "New").Call(Lit("invalid variant payload"))),
											)
										})
									}
									if len(vi.requiredAnyOf) > 0 {
										variant.Var().Id("anyOfMatch").Bool()
										for _, alternative := range vi.requiredAnyOf {
											variant.BlockFunc(func(candidate *Group) {
												candidate.Id("match").Op(":=").Lit(true)
												for _, rk := range alternative {
													emitAlternativeValueMatch(candidate, "match", rk, vi.alternativeProps[rk])
												}
												candidate.If(Id("match")).Block(Id("anyOfMatch").Op("=").Lit(true))
											})
										}
										variant.If(Op("!").Id("anyOfMatch")).Block(Return(Qual("errors", "New").Call(Lit("invalid variant payload"))))
									}
									variant.Var().Id("v").Id(vi.typeName)
									variant.If(Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("v")).Op("!=").Nil()).Block(Return(Qual("errors", "New").Call(Lit("invalid variant payload"))))
									variant.Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v")
									variant.Return(Nil())
								})
							}
						}
					})
				})
			}
			// required-key match
			for _, vi := range variants {
				if vi.discValue != "" {
					continue
				}
				if vi.isObject && len(vi.required) > 0 {
					obj.BlockFunc(func(h *Group) {
						h.Var().Id("v").Id(vi.typeName)
						h.Var().Id("match").Bool().Op("=").Lit(true)
						for _, rk := range vi.required {
							property := vi.properties[rk]
							allowsNull := definitionAllowsNull(schema, property, make(map[*load.Definition]bool))
							h.BlockFunc(func(required *Group) {
								required.List(Id("raw"), Id("ok")).Op(":=").Id("m").Index(Lit(rk))
								required.If(Op("!").Id("ok")).Block(Id("match").Op("=").Lit(false))
								if !allowsNull {
									required.If(Id("ok").Op("&&").Qual("bytes", "Equal").Call(Qual("bytes", "TrimSpace").Call(Id("raw")), Index().Byte().Parens(Lit("null")))).Block(
										Id("match").Op("=").Lit(false),
									)
								}
								required.If(Id("ok")).BlockFunc(func(present *Group) {
									present.Var().Id("value").Add(jenTypeFor(property))
									present.If(Qual("encoding/json", "Unmarshal").Call(Id("raw"), Op("&").Id("value")).Op("!=").Nil()).Block(
										Id("match").Op("=").Lit(false),
									)
								})
							})
						}
						if len(vi.requiredAnyOf) > 0 {
							h.Var().Id("anyOfMatch").Bool()
							for _, alternative := range vi.requiredAnyOf {
								h.BlockFunc(func(candidate *Group) {
									candidate.Id("candidateMatch").Op(":=").Lit(true)
									for _, rk := range alternative {
										emitAlternativeValueMatch(candidate, "candidateMatch", rk, vi.alternativeProps[rk])
									}
									candidate.If(Id("candidateMatch")).Block(Id("anyOfMatch").Op("=").Lit(true))
								})
							}
							h.If(Op("!").Id("anyOfMatch")).Block(Id("match").Op("=").Lit(false))
						}
						h.If(Id("match")).Block(
							If(Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("v")).Op("!=").Nil()).Block(Return(Qual("errors", "New").Call(Lit("invalid variant payload")))),
							Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v"),
							Return(Nil()),
						)
					})
				}
			}
		}).Else().Block(
			// Not an object (e.g., primitive union variant) or invalid JSON.
			If(List(Id("_"), Id("ok")).Op(":=").Id("err").Assert(Op("*").Qual("encoding/json", "UnmarshalTypeError")), Op("!").Id("ok")).Block(Return(Id("err"))),
		)
		// For array variants with required keys on object items, try key-based matching first.
		g.Var().Id("arr").Index().Map(String()).Qual("encoding/json", "RawMessage")
		g.If(Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("arr")).Op("==").Nil()).BlockFunc(func(arr *Group) {
			for _, vi := range variants {
				if !vi.isArray || len(vi.arrayItemRequired) == 0 {
					continue
				}
				arr.BlockFunc(func(h *Group) {
					h.Var().Id("v").Id(vi.typeName)
					h.Var().Id("match").Bool().Op("=").Lit(true)
					h.For(List(Id("_"), Id("elem")).Op(":=").Range().Id("arr")).BlockFunc(func(loop *Group) {
						for _, rk := range vi.arrayItemRequired {
							loop.If(List(Id("_"), Id("ok")).Op(":=").Id("elem").Index(Lit(rk)), Op("!").Id("ok")).Block(Id("match").Op("=").Lit(false))
						}
					})
					h.If(Id("match")).Block(
						If(Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("v")).Op("!=").Nil()).Block(Return(Qual("errors", "New").Call(Lit("invalid variant payload")))),
						Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v"),
						Return(Nil()),
					)
				})
			}
		})
		// fallback: try decode sequentially
		for _, vi := range variants {
			if vi.literalConst != nil {
				g.Block(
					Var().Id("v").Id(vi.typeName),
					If(
						Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("v")).Op("==").Nil().Op("&&").
							Id("v").Op("==").Id(vi.typeName).Call(Lit(vi.literalConst)),
					).Block(
						Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v"),
						Return(Nil()),
					),
				)
				continue
			}
			if vi.isObject && (len(vi.required) > 0 || len(vi.requiredAnyOf) > 0) {
				continue
			}
			g.Block(
				Var().Id("v").Id(vi.typeName),
				If(Qual("encoding/json", "Unmarshal").Call(Id("b"), Op("&").Id("v")).Op("==").Nil()).Block(
					Id("u").Dot(vi.fieldName).Op("=").Op("&").Id("v"),
					Return(Nil()),
				),
			)
		}
		g.Return(Qual("errors", "New").Call(Lit("no matching variant for union")))
	})
	// Marshal
	f.Func().Params(Id("u").Id(name)).Id("MarshalJSON").Params().Params(Index().Byte(), Error()).BlockFunc(func(g *Group) {
		for _, vi := range variants {
			g.If(Id("u").Dot(vi.fieldName).Op("!=").Nil()).BlockFunc(func(gg *Group) {
				// Null-only variant encodes to JSON null
				if vi.isNull {
					gg.Return(Qual("encoding/json", "Marshal").Call(Nil()))
				} else if vi.literalConst != nil {
					gg.Return(Qual("encoding/json", "Marshal").Call(Id(vi.typeName).Call(Lit(vi.literalConst))))
				} else {
					gg.List(Id("_b"), Id("_e")).Op(":=").Qual("encoding/json", "Marshal").Call(Op("*").Id("u").Dot(vi.fieldName))
					gg.If(Id("_e").Op("!=").Nil()).Block(Return(Index().Byte().Values(), Id("_e")))
					if !vi.isObject || vi.preserveRaw {
						// Non-object variants (e.g., arrays/primitives) are already in final wire shape.
						gg.Return(Id("_b"), Nil())
						return
					}
					// Marshal object variants through RawMessage values so discriminator
					// injection does not coerce metadata numbers through float64.
					gg.Var().Id("m").Map(String()).Qual("encoding/json", "RawMessage")
					gg.If(Qual("encoding/json", "Unmarshal").Call(Id("_b"), Op("&").Id("m")).Op("!=").Nil()).Block(Return(Index().Byte().Values(), Qual("errors", "New").Call(Lit("invalid variant payload"))))
					// Inject const discriminants
					if len(vi.constPairs) > 0 {
						for _, kv := range vi.constPairs {
							gg.Id("m").Index(Lit(kv[0])).Op("=").Qual("encoding/json", "RawMessage").Call(Lit(strconv.Quote(kv[1])))
						}
					}
					gg.Return(Qual("encoding/json", "Marshal").Call(Id("m")))
				}
			})
		}
		g.Return(Index().Byte().Values(), Nil())
	})
	f.Line()

	// oneOf requires exactly one variant, anyOf at least one.
	f.Func().Params(Id("u").Op("*").Id(name)).Id("Validate").Params().Params(Error()).BlockFunc(func(g *Group) {
		g.Var().Id("count").Int()
		for _, vi := range variants {
			g.If(Id("u").Dot(vi.fieldName).Op("!=").Nil()).Block(Id("count").Op("++"))
		}
		if exactlyOne {
			g.If(Id("count").Op("!=").Lit(1)).Block(
				Return(Qual("errors", "New").Call(Lit(name + " must have exactly one variant set"))),
			)
		} else {
			g.If(Id("count").Op("<").Lit(1)).Block(
				Return(Qual("errors", "New").Call(Lit(name + " must have at least one variant set"))),
			)
		}
		// Re-decode the selected variant's wire representation. This applies the
		// same required-property, nullability, and primitive type checks used for
		// inbound JSON to values assembled programmatically by SDK callers.
		g.List(Id("encoded"), Id("err")).Op(":=").Qual("encoding/json", "Marshal").Call(Op("*").Id("u"))
		g.If(Id("err").Op("!=").Nil()).Block(Return(Id("err")))
		g.Var().Id("decoded").Id(name)
		g.If(Id("err").Op(":=").Qual("encoding/json", "Unmarshal").Call(Id("encoded"), Op("&").Id("decoded")), Id("err").Op("!=").Nil()).Block(
			Return(Qual("fmt", "Errorf").Call(Lit(name+": %w"), Id("err"))),
		)
		g.Return(Nil())
	})
	f.Line()
}
