// Code generated by acp-go-generator; DO NOT EDIT.

package v2

// ProtocolVersionNumber is the ACP protocol version supported by this SDK.
const ProtocolVersionNumber = 2

// Agent method names
const (
	AgentMethodAuthLogin              = "auth/login"
	AgentMethodAuthLogout             = "auth/logout"
	AgentMethodInitialize             = "initialize"
	AgentMethodSessionCancel          = "session/cancel"
	AgentMethodSessionClose           = "session/close"
	AgentMethodSessionDelete          = "session/delete"
	AgentMethodSessionList            = "session/list"
	AgentMethodSessionNew             = "session/new"
	AgentMethodSessionPrompt          = "session/prompt"
	AgentMethodSessionResume          = "session/resume"
	AgentMethodSessionSetConfigOption = "session/set_config_option"
)

// Client method names
const (
	ClientMethodElicitationComplete      = "elicitation/complete"
	ClientMethodElicitationCreate        = "elicitation/create"
	ClientMethodSessionRequestPermission = "session/request_permission"
	ClientMethodSessionUpdate            = "session/update"
)
